name: Publish to EC2 AWS

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish to EC2 AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: create Pem file
        run: |
          echo $PEM_KEY >> key.pem
          cat key.pem
        shell: bash
        env:
          PEM_KEY : ${{secrets.KEY}}
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY }}
      # - name: Create SSH key
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_PRIVATE_KEY" > ../private.key
      #     sudo chmod 600 ../private.key
      #     echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      #   shell: bash
      # - name: Add to known hosts
      #   run: ssh-keyscan -H {{ secrets.PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: SSH to ec2
        run: ssh ubuntu@${{ secrets.PUBLIC_IP }} -i key.pem
      - name: cd to project
        run: cd shangrila-web-application
      - name: Prune docker
        run: sudo docker system prune
      - name: Docker down
        run: sudo docker-compose down
      - name: Docker up with build
        run: sudo docker-compose up --build -d