name: Deploy EC2
on:
  push:
    branches:
      - test
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Permission
        run: chmod +x execute.sh
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PUBLIC_IP }}
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: rsync over ssh 
        run: ./execute.sh